### ISSUE TITLE
Accidental merge

### ISSUE THREAD

**Issue by EwanSC** [EwanSC/BromansCoopey#3]
Accidentally merged phd into master - how do I revert back to before this merge? @Denubis

**Comment by EwanSC** [comment]
I think I have resolved issue: followed these instructions https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request

**Comment by Denubis** [comment]
I use three sites:
https://ohshitgit.com/
https://sethrobertson.github.io/GitFixUm/fixup.html
https://github.com/k88hudson/git-flight-rules
